markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

url: https://accis.github.io
baseurl: /StyleGuide/


collections:
  styleguide:
    output: true
    permalink: /:collection/:path/


defaults:
  - scope:
      path: ""
      type: styleguide
    values:
      layout: single
      classes: wide
      toc: true
      read_time: true
      sidebar:
        nav: "docs"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"

