markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

include:
  - _pages

collections:
  styleguide:
    output: true
    permalink: /:collection/:path/
    order:
      - code_for_readability.md
      - IDEs_and_tools.md


defaults:
  - scope:
      path: ""
      type: styleguide
    values:
      layout: single
      classes: wide
      sidebar:
        nav: "docs"
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"

